config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :plays do
    resources :reviews
  end

  root to: 'plays#index'
end

app/models/category.rb
class Category
  include Mongoid::Document
  include Mongoid::Timestamps

  field :name, type: String

  has_many :plays
  validates_presence_of :_id
end

app/models/play.rb
class Play
  include Mongoid::Document
  include Mongoid::Timestamps
  include Mongoid::Paperclip

  field :title, type: String
  field :description, type: String
  field :director, type: String
  field :user_id, type: Integer
  field :category_id, type: Integer

  belongs_to :user
  belongs_to :category
  has_many :reviews


  has_mongoid_attached_file :play_img, styles: { :large => "475x325>", :medium => "350x250>", :thumb => "100x100>" },
                                  default_url: "/images/:style/missing.png",
                                  path: ":rails_root/public/images/:id/:style/:filename",
                                  url: "/images/:id/:style/:filename",
                                  :convert_options => { :all => '-background white -flatten +matte' }
 validates_attachment_content_type :play_img, content_type: /\Aimage\/.*\Z/
 validates_presence_of :title, :description, :director, :category
end

app/models/review.rb
class Review
  include Mongoid::Document
  include Mongoid::Timestamps

  field :rating, type: Integer
  field :comment, type: String
  field :user_id, type: Integer
  field :play_id, type: Integer

  belongs_to :user
  belongs_to :play
end

app/models/user.rb
class User
  include Mongoid::Document
  include Mongoid::Timestamps
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  ## Database authenticatable
  field :email,              type: String, default: ""
  field :encrypted_password, type: String, default: ""

  ## Recoverable
  field :reset_password_token,   type: String
  field :reset_password_sent_at, type: Time

  ## Rememberable
  field :remember_created_at, type: Time

  ## Trackable
  field :sign_in_count,      type: Integer, default: 0
  field :current_sign_in_at, type: Time
  field :last_sign_in_at,    type: Time
  field :current_sign_in_ip, type: String
  field :last_sign_in_ip,    type: String

  ## Confirmable
  # field :confirmation_token,   type: String
  # field :confirmed_at,         type: Time
  # field :confirmation_sent_at, type: Time
  # field :unconfirmed_email,    type: String # Only if using reconfirmable

  ## Lockable
  # field :failed_attempts, type: Integer, default: 0 # Only if lock strategy is :failed_attempts
  # field :unlock_token,    type: String # Only if unlock strategy is :email or :both
  # field :locked_at,       type: Time

  has_many :plays
  has_many :categories
  has_many :reviews
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!, except: [:index, :show]
end

app/controllers/plays_controller.rb
class PlaysController < ApplicationController
  before_action :find_play, only: [:show, :edit, :update, :destroy]
  def index
    if  params[:category].blank?
      @plays = Play.all.order('create_at DESC')
    else
      @category_id = Category.find_by(name: params[:category]).id
      @plays = Play.where(category_id: @category_id).order('create_at DESC')
    end
  end

  def new
    @play = current_user.plays.build
    @categories = Category.all.map{ |c| [c.name, c.id]}
  end

  def show
    if @play.reviews.blank?
      @average_review = 0
    else
      @average_review = @play.reviews.avg(:rating).round(2)
    end
  end

  def create
    @play = current_user.plays.build(play_params)
    @play.category_id = params[:category_id]
    if @play.save
      redirect_to root_path
    else
      render :new
    end
  end

  def edit
    @categories = Category.all.map{ |c| [c.name, c.id]}
  end

  def update
   @play.category_id = params[:category_id]
   if  @play.update(play_params)
      redirect_to play_path
   else
     render :edit
   end
  end

  def destroy
    @play.destroy
    redirect_to root_path
  end

  private

  def find_play
    @play = Play.find(params[:id])
  end

  def play_params
    params.require(:play).permit([:title, :director, :description, :category_id, :play_img])
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :find_play
  before_action :find_reviews, only: [:edit, :update, :destroy]
  def new
    @review = Review.new
  end

  def create
    @review = Review.new(review_params)
    @review.play_id = @play.id
    @review.user_id = current_user._id

    if @review.save
      redirect_to play_path(@play)
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @review.update(review_params)
      redirect_to play_path(@play)
    else
      render :edit
    end
  end

  def destroy
   @review.destroy
   redirect_to play_path(@play)
  end

  private

  def find_play
    @play = Play.find(params[:play_id])
  end

  def find_reviews
    @review = Review.find(params[:id])
  end


  def review_params
    params.require(:review).permit([:rating, :comment])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/plays_helper.rb
module PlaysHelper
end

app/views/layouts/application.html.slim
doctype html
html
  head
    title Broadway
    = csrf_meta_tags

    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'

  body
    nav.navbar.navbar-default
      .container
        .navbar-header
          = link_to 'Broadway', root_path, class: 'navbar-brand'
        ul.nav.navbar-nav.navbar-right
          - unless user_signed_in?
            li= link_to 'Log in', new_user_session_path
            li= link_to 'Sign Up', new_user_registration_path
          - else
            ul.nav.navbar-nav
              li.dropdown
                a.dropdown-toggle data-toggle="dropdown" href="#" aria-expended='false' role='button'
                  | Gender
                  span.caret
                ul.dropdown-menu role='menu'
                  - Category.all.each do |category|
                    li class="#{ 'active' if params[:category] == category.name }"
                      =link_to category.name, plays_path(category: category.name), class: 'link'

            li= link_to 'New Play', new_play_path, class: 'pull-left'
            li=link_to 'Sign Out', destroy_user_session_path, method: :delete, notice: 'Good Bey!'
    .container
      - flash.each do |name, msg|
        = content_tag :div, msg, class: "alert alert-#{name}"

      = yield

app/views/plays/_form.html.slim
= simple_form_for @play, html: { multipart: true } do |f|
  - unless !@play.new_record
    = select_tag(:category_id, options_for_select(@categories), prompt: 'Select Category', include_blank: false)
  - else
    = f.select :category_id, @categories unless @play.new_record
  .form-group
    br
    = f.file_field :play_img, class: 'form-control'
  .form-group
    = f.input :title, label: 'Play', class: 'form-control'
  .form-group
    = f.input :description, as: :text, class: 'form-control'
  .form-group
    = f.input :director, class: 'form-control'
  .form-group
  = f.button :submit, class: 'btn btn-default'

app/views/plays/create.html.slim
h1 Plays#create
p Find me in app/views/plays/create.html.slim

app/views/plays/destroy.html.slim
h1 Plays#destroy
p Find me in app/views/plays/destroy.html.slim

app/views/plays/edit.html.slim
.col-md-10.col-md-offset-1
  .new-play-form
    h1 Edit Broadway Play
    = render 'form'

app/views/plays/index.html.slim
h1.current-category
  = params[:category]

- if @plays.count == 0
    h3 There are no play for this category
- else
  .row
    - @plays.each do |play|
      .col-md-3
        a href="/plays/#{play.id}"
          = image_tag play.play_img.url(:medium), class: 'play'

app/views/plays/new.html.slim
.col-md-10.col-md-offset-1
  .new-play-form
    h1 Play with us
    = render 'form'

app/views/plays/show.html.slim
.row
  .col-md-4
    = image_tag @play.play_img.url(:large), class: 'play-show'
  .col-md-8
    .play-info
      h2.play-title= @play.title
      h3.play-director
        span
          | From
          =< @play.director
      h4.play-director= @play.category.name
      h4.avg-rating Average Rating
      .average-review-rating data-score="#{@average_review}"
      span.number-of-reviews
        em From:
        =<> @play.reviews.count
        | reviews
      p.play-decs= @play.description
      .links.btn-group
        - if user_signed_in? && @play.user_id == current_user._id
          = link_to 'edit', edit_play_path(@play), class: 'btn btn-info'
          = link_to 'delete', play_path(@play), method: :delete, data: { confirm: 'are your sure?'}, class: 'btn btn-danger'

.row
  .col-md-12
    .reviews
      h1 Review
      = render @play.reviews
      .form-group
        = link_to 'Add Review', new_play_review_path(@play), class: 'btn-custom'
javascript:
  $('.review-rating').raty({
    readOnly: true,
    score: function() {
      return $(this).attr('data-score');
    },
    path: '/assets/'
  });
  $('.average-review-rating').raty({
    readOnly: true,
    path: '/assets/',
    score: function() {
    return $(this).attr('data-score')}
  });

app/views/plays/update.html.slim
h1 Plays#update
p Find me in app/views/plays/update.html.slim

app/views/reviews/_form.html.slim
- if @review.new_record?
  = simple_form_for([@play, @play.reviews.build]) do |f|
    #rating-form
      label Ratin
    = f.input :comment
    = f.button :submit, class: 'btn-custom2'
- else
  = simple_form_for([@play, @review]) do |f|
    #rating-form
      label Rating
    = f.input :comment
    = f.button :submit, class: 'btn-custom2'


javascript:
  $('#rating-form').raty({
    path: '/assets/',
    scoreName: 'review[rating]'
  });

app/views/reviews/_review.html.slim
.review
  .review-rating data-score="#{review.rating}"
  p.review-comment= review.comment
  - if user_signed_in? && review.user_id == current_user.id
    .links.btn-group
      = link_to 'Edit', edit_play_review_path(review.play, review),  class: 'btn btn-custom'
      = link_to 'Delete', play_review_path(review.play, review), method: :delete, data: { confirm: 'are you sure?' }, class: 'btn btn-custom'

app/views/reviews/edit.html.slim
.col-md-10.col-md-offset-1
  .edit-review-form
    h1 Edit Review
    = render 'form'

app/views/reviews/new.html.slim
.col-md-10.col-md-offset-1
  .new-review-form
    h1 Post Review
    = render 'form'